### PR TITLE
[ADD] macos rename computer script

### PR DESCRIPTION
**Pull request by jpros**
Added script to rename macos computer.
Already tested in a MacBook Pro m1 running macOS Monterey.

### CODE REVIEW

**Comment by bbrendon** [comment]
Why wasn't `scutil --set HostName` included?

**Comment by jpros** [comment]
@bbrendon, I used the "set HostName". After further research, the LocalHostName works fine for ".local" hostnames, so I removed the "set HostName".

The "set HostName" option is only useful when you have an FQDN associated with the machine, and in my POV, that's not a common use case for Macs.

We could create another script for those who want to have an FQDN associated, but in the scenario of my company, we wouldn't use that.

**Comment by silversword411** [comment]
Why not one script, with a switch to choose which method?

**Comment by silversword411** [comment]
Closing

**Pull request closed without merging**
