### PR TITLE
Update Win_ScreenConnectAIO.ps1

### PR DESCRIPTION
**Pull request by bionemesis**
Add missing actions for start/stop.

### CODE REVIEW

**Comment by silversword411** [comment]
I'm not using this, I think this is fine would like script creator @bradhawkins85 to comment

**Comment by bradhawkins85** [comment]
I'll take a look at this later today, should be fine though.

**Comment by bradhawkins85** [comment]
> Add missing actions for start/stop.

The script was designed to toggle the service so start/stop actions were not required.
I feel adding these changes may cause functionality issues for anyone already using the script in the current manner. Would also require changing the action every time depending on if the service needs to be started or stopped.

Correct me if I am wrong regarding your intentions with the code changes?

**Comment by silversword411** [comment]
Discussion started here: https://discord.com/channels/736478043522072608/744281869499105290/957672818609356941

**Comment by silversword411** [comment]
Was kind of waiting for guidance on you two @bradhawkins85 @bionemesis to hash out the best path: integrate this PR/switch it out/make different scripts for 2 different uses. 

Guidance needed

**Comment by wh1te909** [comment]
@bradhawkins85 sent me the updated code on discord for this and I added it in https://github.com/amidaware/community-scripts/commit/f0489d3c2777344fa58f77b64ab4f3d42df257cb so this is now complete thanks

**Pull request closed without merging**
