### PR TITLE
more complete RDP

### PR DESCRIPTION
**Pull request by bbrendon**

### CODE REVIEW

**Comment by dinger1986** [comment]
can we parameter this for username etc so it can be added, if its ignored then it doesnt set the username etc.

Also for the comments they would be better in a comment header at the top

**Comment by bbrendon** [comment]
I wasn’t really looking to rewrite it in powershell :)

**Comment by dinger1986** [comment]
Lol, one of my guys is doing it now anyway cause hes wanting to add in a variable for the user :)

**Comment by silversword411** [comment]
ChatGPT....

**Comment by bbrendon** [comment]
I just ran this on a VM without issue.

**Comment by dinger1986** [comment]
Tbf nothing fundamental has changed with it so will work fine, same as the old one.

I need to chase up the powershell script

**Comment by bbrendon** [comment]
rdp won't with if you don't start it. seems pretty important.

**Comment by bbrendon** [comment]
Also, it won't work if its disabled as well.

**Comment by dinger1986** [comment]
Hmmm, weird thing is that I wrote that script pre covid and never had to start it or change it from disabled. It's always just worked.

Not disagreeing at all, yours is neater.

@silversword411 you can merge.

I'll get a powershell script submitted soon

**Comment by bbrendon** [comment]
Did you test on Win11? It didn't work for me which is why I submitted a PR.

**Comment by silversword411** [comment]
Would really like a AIO rdp enable/disable script as an alternative...and fix TRMM install rdp option which doesn't work either.

**Pull request merged**
