### PR TITLE
Delete scripts/Win_RustDesk_GetID.ps1

### PR DESCRIPTION
**Pull request by dinger1986**

### CODE REVIEW

**Comment by dinger1986** [comment]
script doesnt work, best to work from docs and keep everything out of scripts for RustDesk

**Comment by silversword411** [comment]
I've been debating how to handle the existing rustdesk stuff.

Rustdesk definitely in flux atm. Probably best to pull, if there are installs in the field this is going to mess with status.

We still have the outstanding big about deleting community scripts causing problems in the field. Need to refresh memory and check before accepting this.

**Comment by dinger1986** [comment]
I think its best to keep it in the docs, one place to update, its reliant on users having a custom field setup as well.

The script doesnt work with 1.2.2 so pointless having it

**Comment by NiceGuyIT** [comment]
> We still have the outstanding big about deleting community scripts causing problems in the field. Need to refresh memory and check before accepting this.

The issue is if a community script is deleted, the corresponding check (and task?) will be silently deleted when people update. It's better to update the script with a message and exit with an error. That will signal to the observant user that the script is no longer working. If people don't monitor for errors from scripts, that's on them.

**Comment by dinger1986** [comment]
ok yes that makes sense, its just to try and not have to maintain scripts in 2 places and then rustdesk update something and people say well trmm isnt up to date

**Comment by silversword411** [comment]
This was the one: https://github.com/amidaware/tacticalrmm/issues/1486

Should probably have some kind of obvious naming convention and keyword(s).

**Comment by dinger1986** [comment]
So we should rename the script to `!!!Broken - Read Docs` or something similar?

**Comment by dinger1986** [comment]
So we should rename the script to `!!!Broken - Read Docs` or something similar?

**Pull request closed without merging**
