### PR TITLE
New Community Script: Reboot

### PR DESCRIPTION
**Pull request by silversword411**

### CODE REVIEW

**Comment by dinger1986** [comment]
testwait

Doesnt work for me, changed afew things but not passing $Wait correctly

**Comment by silversword411** [comment]
A 120 second wait on a 90 second killed script definitely won't work 😂

Probably need to update timeout to 12hrs or something crazy or agent is going to kill it while ps is waiting.

**Comment by dinger1986** [comment]
changed timeout to 300 seconds and wait to 120 seconds and still get the same

**Comment by dinger1986** [comment]
Id just do it 
```
param(
    [int]$Wait
)

if ($Wait) {
    shutdown -r -t $Wait
}
else {
    Restart-Computer -Force
}
```

**Comment by silversword411** [comment]
> Id just do it

Works for me! :)

**Pull request merged**
